### ISSUE TITLE
PUT to transactions endpoint doesn't return a transaction ID

### ISSUE THREAD

**Issue by Ampakinetic** [Oxycoin/oxy-node#8]
I'm not sure if I'm doing something wrong, but for some reason the result from a successful send transaction no longer returns a transaction ID.  It returns "success: true", and the coins move, but no sign of a transactionId in the response. This is different to how it used to work in earlier versions.

Can anyone shed any light on where or how to get at this information?

Thank you.

**Comment by vekexasia** [comment]
Hello @Ampakinetic sorry for the delayed response.

I'm not sure i'm following. In oxy-node 1.0.3 the PUT /api/transactions endpoint is no longer available. I think you're talking about "POST" /peer/transactions which used to return {success: true} and the transactionID.

When using such endpoint you're already providing a valid (and signed) transaction that should also contain a transaction id (even if the endpoint does not strictly require it).  So you should already have such info.

If you're using javascript or typescript to sign the transaction you could use [dpos-offline](https://github.com/vekexasia/dpos-offline) It will provide all the functionalities you probably need to build and offline-sign a transaction. 

If you're using another programming language other than js/ts to create the transaction please let us know the libraries you're using and possibly share a code snippet to help us get this issue fixed.

**Comment by Ampakinetic** [comment]
Thank you!
